import Link from "next/link";
import { APP_NAME } from "../../lib/core/config";

/**
 * The mark and the name, together, everywhere the product signs itself.
 *
 * Four places drew this by hand with the same class string copied between them
 * — Navbar.tsx (the landing page and every door screen), CardsSidebar.tsx (the
 * head of the rail), MarketingFooter.tsx, and the loading fallback. That is the
 * arrangement Navbar.tsx itself argues against one file over: "One component so
 * a change to one applies to both, rather than [each] keeping their own copy to
 * drift apart by hand." Adding an image to four copies is exactly the change
 * that would have proven the point, so it is one component first.
 *
 * The orb comes from the iOS app's icon — the same sphere without its tile, so
 * the site and the installed app are recognisably the same product. It is
 * generated by `Tools/GenerateAppIcon.swift` in the cardorb-ios repository and
 * handed over as files; see `/brand`, ADR-0048 and ADR-0049 for which cut goes where.
 */

/**
 * 24px, against a name set at --fs-label (15–16px).
 *
 * The shadowed cut draws the sphere at roughly 80% of its box so the contact
 * shadow has somewhere to fall, so the ball reads at about 19px here — a little
 * over the name's cap height, which is where a mark beside a word wants to sit.
 * Swapping in the unshadowed cut at this size would look a size too big.
 */
const MARK_PX = 24;

/**
 * The shadow is not part of the mark, so it does not get a vote on where the
 * mark sits.
 *
 * `items-center` centres the *file*, and in the shadowed cut the file is not the
 * ball: measured on orb-shadow-256.png, the sphere's body runs y 11–214 in a 256
 * box, so its centre is at 112.5 where the box's is at 128 — the extra 40-odd
 * pixels below it are the room the contact shadow falls into. Centre the box and
 * the ball rides 15.5/256 of the height high, which is 1.4px at 24px and reads,
 * next to a word, as a logo that is not quite sitting down.
 *
 * So the image is pushed back down by exactly that fraction. The shadow now
 * hangs slightly below the text's baseline, which is what a shadow is supposed
 * to do.
 *
 * The word needs no matching correction, which is luck rather than design:
 * "Card Orb" has no descender, and in Inter the ink's midpoint between baseline
 * and cap height lands within a thousandth of an em of the line box's own
 * centre. Centring the line box centres the letters. A name with a descender in
 * it would not be so tidy.
 */
const MARK_NUDGE = "translate-y-[6.05%]";

/**
 * The name's own typography, unchanged from the four copies this replaces.
 * --font-main and the tighter tracking are what make it read as a mark rather
 * than as a word that happens to be first on the page.
 */
const WORD =
  "text-primary font-body [font-size:var(--fs-label)] font-bold tracking-[-0.03em]";

const ROW = "inline-flex items-center gap-2";

/**
 * AVIF with a PNG fallback, which is not premature: the orb is a smooth
 * gradient and PNG stores those badly — 6 KB against 49 KB at 256px, for a
 * picture no eye can tell apart. Width descriptors rather than 1x/2x, so the
 * browser solves the density itself; there is no source small enough to be the
 * literal 1x of a 24px box and inventing one would be a fourth file to keep.
 *
 * alt="" because this sits next to the word "Card Orb". A screen reader
 * announcing "Card Orb Card Orb" is worse than one announcing it once.
 */
function Mark() {
  return (
    <picture className="flex-none">
      <source
        srcSet="/brand/orb-shadow-64.avif 64w, /brand/orb-shadow-128.avif 128w, /brand/orb-shadow-256.avif 256w"
        sizes={`${MARK_PX}px`}
        type="image/avif"
      />
      <img
        src="/brand/orb-shadow-64.png"
        srcSet="/brand/orb-shadow-64.png 64w, /brand/orb-shadow-128.png 128w, /brand/orb-shadow-256.png 256w"
        sizes={`${MARK_PX}px`}
        width={MARK_PX}
        height={MARK_PX}
        alt=""
        aria-hidden="true"
        className={`block ${MARK_NUDGE}`}
      />
    </picture>
  );
}

/**
 * `href` decides what this is. With one it is the way home, which is what the
 * nav and the rail want; without one it is a signature, which is what the
 * footer and the loading fallback want — a fallback in particular should not be
 * pressable, since there is nothing behind it yet.
 *
 * The label stays "Card Orb home" on the link, as it was: it contains the
 * visible word, so it says where the link goes without renaming what it shows.
 */
export default function Wordmark({ href, className }: { href?: string; className?: string }) {
  const inner = (
    <>
      <Mark />
      <span>{APP_NAME}</span>
    </>
  );

  if (href === undefined) {
    return <span className={[ROW, WORD, className].filter(Boolean).join(" ")}>{inner}</span>;
  }

  return (
    <Link
      href={href}
      aria-label={`${APP_NAME} home`}
      className={[ROW, WORD, "no-underline", className].filter(Boolean).join(" ")}
    >
      {inner}
    </Link>
  );
}
