// Generated by scripts/extract-theme-values.mjs from styles/theme.css.
// Do not edit: npm run check regenerates this and fails on a diff.
//
// These are the only design values that exist outside a stylesheet, and they
// exist because their four readers cannot read one — the web manifest is JSON,
// viewport.themeColor is a JS object, and both OG images are drawn by Satori
// without a browser. Every value here is resolved from styles/theme.css, so the
// stylesheet stays the single source and this cannot drift from it.

export type ColourPair = { light: string; dark: string };

export const colour = {
  label: { light: "#171717", dark: "#fafafa" },
  labelSecondary: { light: "#404040", dark: "#d4d4d4" },
  labelTertiary: { light: "#525252", dark: "#a1a1a1" },
  bgGrouped: { light: "#fafafa", dark: "#171717" },
  bgSurface: { light: "#ffffff", dark: "#0a0a0a" },
} satisfies Record<string, ColourPair>;

/** Card Orb's radius scale, by name — tailwind-merge needs the names, not the values. */
export const radiusNames = [
  "btn",
  "control",
  "control-inner",
  "orb-lg",
  "orb-md",
  "orb-sm",
  "orb-xs",
  "pill",
] as const;
