/**
 * Where a card is on Cardmarket. Split out of cards.ts, where it sat beside
 * matching and collection assembly with no seam between them.
 */

/* tcgId -> the path to that card on Cardmarket. Generated, and generated by
   hand: see scripts/cardmarket-links.mjs and cardmarketUrl below. */
import LINKS from "./cardmarket-links.generated.json";

/**
 * The straight answer is its own product page, and the path to it is generated
 * by scripts/cardmarket-links.mjs: their catalogue names the product, the header
 * of that script says how the two halves of the URL are built and why the
 * expansion half has to be checked by hand.
 *
 * The fallback is a search on the card's name, and the important part of it is
 * what is *not* in the query. It used to be name plus set name, which found
 * nothing at all: a product there is called "Alakazam [Damage Swap | Confuse
 * Ray]", so the set name matches no product on the site and every search came
 * back empty. The name alone is broad but it is never empty.
 *
 * language=1&minCondition=2 is English, Near Mint or better, which is the exact
 * copy the price beside this link is an estimate for (see NM_BANDS in
 * price-basis.mjs). Without it their page opens on every condition in every
 * language and the cheapest listing on screen is a played Japanese one.
 */
export function cardmarketUrl(id: string, name: string): string {
  const path = (LINKS as Record<string, string | undefined>)[id];
  return path
    ? `https://www.cardmarket.com/en/Pokemon/Products/Singles/${path}?language=1&minCondition=2`
    : `https://www.cardmarket.com/en/Pokemon/Products/Search?searchString=${encodeURIComponent(name)}`;
}
