/**
 * The whole card collection, grouped by set. Everything binder shows is a view
 * of what this returns.
 *
 * It came from the portfolio at bartdunweg.com, where it fed /cards, and it is
 * the reason this project starts with something rather than with a scaffold:
 * two years of matching a hand-kept Notion database against three card
 * catalogues live in here, and none of that is worth writing twice. The parts
 * that were about that site (its image manifest, its cover-art resolver) are in
 * ./util now, hollowed out, with a note saying what they used to do.
 *
 * The unit is the set, not the card. Resolving one card at a time costs one to
 * four requests, which is the right trade for a single cover and the wrong one
 * for a collection: a few hundred cards would mean a few hundred round trips on
 * every revalidation. TCGdex returns every card in a set, with its image, in
 * one response, so the cost scales with the number of sets pulled from rather
 * than the number of cards owned. Only the cards that miss fall back to a
 * per-card lookup.
 *
 * Server-side only: it reads NOTION_TOKEN from the environment. Fails soft. No
 * token or a Notion outage returns an empty list and the surface above says so,
 * rather than inventing a collection.
 */

import { DAY, localise, measure, norm } from "./util";
import { speciesOf } from "./pokedex";
import { LOCALE } from "./config";
/* tcgId -> the path to that card on Cardmarket. Generated, and generated by
   hand: see scripts/cardmarket-links.mjs and cardmarketUrl below. */
import LINKS from "./cardmarket-links.generated.json";
import { ptcgLogo, ptcgScan } from "./ptcg";
import {
  NOTION_VERSION,
  TRADING_DATABASE,
  text,
  type NotionPage,
  type NotionProperty,
} from "./notion";

/**
 * One printing of a card: a rarity, and whether that printing is in the binder
 * or on the wishlist. The same card is often held twice, normally and as a
 * reverse holo, and those are two of these rather than two cards.
 */
export type Variant = {
  /** "Non-holo", "Reversed Holo", "Illustration Rare". */
  rarity: string | null;
  /** Notion's Collection checkbox: false means it is wanted, not held. */
  owned: boolean;
};

/**
 * What a card costs, from Cardmarket via TCGdex, in euros.
 *
 * This used to be Cardmarket's `low` under the label "From", on the reasoning
 * that the lowest listing is what you would actually pay. Measured, it is not a
 * price at all. It is the lowest listing at any condition in any language, and
 * over 269 sampled cards the median `low` came to 16% of the same card's trend.
 * Worse, 421 of the 1,211 priced cards in this collection sat under €0.10 and
 * together made up 0.1% of the total: their cheapest listing is a bulk lot, not
 * a card. A third of the binder was valued at a rounding error.
 *
 * So `low` is kept for what it honestly is, a floor, and `market` is what a
 * single copy actually changes hands for. `nm` is the estimate of what an
 * English Near Mint copy is listed at, which is the number a collector means
 * when they ask what a card costs, and which no free feed publishes.
 */
/**
 * The price maths lives in lib/price-basis.mjs, re-exported here so every caller
 * keeps importing it from the same place it always did.
 *
 * It moved out because scripts/snapshot-collection-value.mjs has to put the same
 * number on a card as this file does, and Node 20 cannot import a .ts file. The
 * calibration comments moved with it; that file is where they are now.
 */
import { priceOf } from "./price-basis.mjs";
export { priceOf, shownPrice } from "./price-basis.mjs";
export type { Price } from "./price-basis.mjs";
import type { Price } from "./price-basis.mjs";

const num = (v: unknown) => (typeof v === "number" ? v : null);

export type OwnedCard = {
  /** Set, number and name: unique within the collection, and stable. */
  key: string;
  name: string;
  /** As Notion writes it, usually zero-padded ("088"). */
  number: string;
  /** The Pokémon's type, when the row has one: Fire, Water, Psychic. */
  type: string | null;
  /** The era it belongs to, as recorded: "Base", "Scarlet & Violet". */
  gen: string | null;
  image: string | null;
  /**
   * The same scan at TCGdex' larger size, for when the grid is drawing cards big
   * enough that the small one is being stretched. Null where the picture came
   * from one of the fallback catalogues, which publish a single file.
   */
  imageHigh: string | null;
  /**
   * How big that scan is, where it is one of ours.
   *
   * So the grid can reserve the space before the file arrives. Null for a scan
   * still coming from TCGdex or Limitless, which has not been measured, and the
   * stylesheet's own ratio takes over. See measure() in ./util.
   */
  imageSize: ImageSize;
  /**
   * Which Pokémon this card shows, by National Dex number, or null for the
   * trainers and the energy.
   *
   * Worked out here rather than in the browser. speciesOf() is a scan down a
   * thousand species names looking for the longest one inside the card's name,
   * and /cards used to run it per card while rendering: two thousand cards
   * against a thousand names is two million substring checks in one hydration
   * commit, on a page that already hydrates two thousand grid items. The answer
   * is the same for everyone and never changes, so the server can hold it.
   */
  speciesId: number | null;
  /** Every printing held or wanted, in the order Notion returned them. */
  variants: Variant[];
  /** Whether any printing of it is actually in the binder. */
  owned: boolean;
  /** Null when TCGdex has no match for it, or no price for the match. */
  price: Price | null;
  /**
   * TCGdex's id for the printing this row matched ("sv03-125"), or null when
   * nothing matched. It is the only stable, URL-safe handle a card has, because `key`
   * carries spaces, ampersands and the same dash it is split on, so it is what
   * the detail route is addressed by.
   */
  tcgId: string | null;
};

/** `null` where the picture is not one of ours and so has never been measured. */
export type ImageSize = { width: number; height: number } | null;

export type CardSet = {
  /** Notion's own name for the set, which is what groups the collection. */
  name: string;
  logo: string | null;
  /** The logo's size, for the same reason a card's scan carries one. */
  logoSize: ImageSize;
  /** ISO date, when TCGdex knows the set. Drives the order of the sections. */
  releaseDate: string | null;
  /** How many cards the set has in total, for the "12 of 191" line. */
  total: number | null;
  cards: OwnedCard[];
};

type TcgSet = { id: string; name: string };
type TcgCard = { id: string; localId?: string; name?: string; image?: string };
type TcgSetDetail = {
  id: string;
  name?: string;
  logo?: string;
  /** The little round set icon. The only art some sets have. */
  symbol?: string;
  releaseDate?: string;
  cardCount?: { official?: number; total?: number };
  abbreviation?: { official?: string };
  cards?: TcgCard[];
};

/**
 * A cached GET with a couple of retries.
 *
 * Everything artwork-related on this page goes through here, and the retries
 * are not defensive padding: a build that asks TCGdex for sixty endpoints in a
 * minute gets some of them refused, and each refusal used to be swallowed. One
 * of those refusals landing on the sets index took the artwork off all 1904
 * cards at once, because without the index no set can be resolved at all.
 */
async function json(url: string, label: string) {
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const res = await fetch(url, { next: { revalidate: DAY } });
      if (!res.ok) throw new Error(`${res.status}`);
      return await res.json();
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      if (attempt < 2) {
        await new Promise((r) => setTimeout(r, 400 * (attempt + 1)));
        continue;
      }
      console.error(`TCGdex ${label} failed after 3 attempts:`, message);
      throw err;
    }
  }
}

/**
 * One column off a row, found by name.
 *
 * By name rather than by value, since unlike a country a rarity or a type is
 * not self-identifying: "Rare" and "Fire" could be anything. The name is
 * matched loosely so Rarity, rarity or "Card rarity" all work, and the value is
 * read from whichever shape the property happens to be: select, multi-select,
 * text or number. The database has Rarity, Type and Gen (see the column log
 * below), and this reads all three the same way.
 */
function fieldOf(props: Record<string, NotionProperty>, match: RegExp): string | null {
  for (const [name, p] of Object.entries(props)) {
    if (!match.test(name)) continue;
    const value =
      p.select?.name ??
      (p.multi_select ?? [])
        .map((o) => o.name)
        .filter(Boolean)
        .join(", ") ??
      "";
    const out = value || text(p) || (typeof p.number === "number" ? String(p.number) : "");
    if (out) return out;
  }
  return null;
}

/** Notion pads to three digits, TCGdex mostly agrees but not always. */
const numberForms = (n: string) => [...new Set([n, n.replace(/^0+/, ""), n.padStart(3, "0")])];

/**
 * Promo sets are the one place the two vocabularies genuinely disagree rather
 * than merely differing in punctuation, and no amount of loose matching bridges
 * them: "SV" and "SVP" share no substring with "Scarlet & Violet", and Bart
 * writes "Wizard" where TCGdex writes "Wizards". Everything else in the
 * collection matches on name, so this stays a short list of exceptions rather
 * than becoming a mapping table for all 48 sets.
 */
const SET_ALIASES: Record<string, string> = {
  // A print run, not a set: TCGdex only knows the set.
  "set 1 unlimited": "base1",
  "set 1 shadowless": "base1",
  "set 1": "base1",
  "sv black star promos": "svp",
  "svp black star promos": "svp",
  "wizard black star promos": "basep",
  "wizards black star promos": "basep",
  "swsh black star promos": "swshp",
  "sm black star promos": "smp",
  "xy black star promos": "xyp",
  "bw black star promos": "bwp",
  "hgss black star promos": "hgssp",
  "dp black star promos": "dpp",
  "nintendo black star promos": "np",
};

/**
 * Whether two names are the same card.
 *
 * The check exists to catch numbering that does not line up, where a scan would
 * be of a different Pokémon entirely. Straight equality was too blunt for that
 * job: Bart files a card as "Venusaur" where TCGdex calls it "Venusaur ex", and
 * on a set like 151 that alone accounted for most of the missing artwork.
 *
 * The card-type suffix comes off both sides before comparing, rather than
 * falling back to "does one contain the other", which would happily accept
 * Mewtwo's scan for a card filed as Mew.
 */
const TYPE_SUFFIX = /\s+(ex|gx|v|vmax|vstar|v-union|prime|legend|break|lv\.?\s?x|star|δ)$/i;

/**
 * How many single-character edits apart two strings are, giving up at `cap`.
 *
 * Two rows of the usual matrix rather than the whole thing, and an early exit
 * once every cell in a row is over the cap, because the answer this is asked for
 * is never "how far apart" but "closer than two".
 */
function editDistance(a: string, b: string, cap: number): number {
  if (Math.abs(a.length - b.length) > cap) return cap + 1;
  // Two rows of the matrix, swapped rather than reallocated. The assertions
  // below are the loop bounds restated: every index here is between 0 and
  // b.length, which is the length both rows were made at, and
  // noUncheckedIndexedAccess cannot see that.
  let prev = new Int32Array(b.length + 1);
  let row = new Int32Array(b.length + 1);
  for (let j = 0; j <= b.length; j++) prev[j] = j;
  for (let i = 1; i <= a.length; i++) {
    row[0] = i;
    let best = i;
    for (let j = 1; j <= b.length; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      const cell = Math.min(prev[j]! + 1, row[j - 1]! + 1, prev[j - 1]! + cost);
      row[j] = cell;
      if (cell < best) best = cell;
    }
    if (best > cap) return cap + 1;
    [prev, row] = [row, prev];
  }
  return prev[b.length]!;
}

/* Exported for lib/cards-name.test.ts, which is a list of the real rows this
   had to be widened for and the pairs it still has to refuse. */
export const sameCard = (a: string, b: string) => {
  const bare = (s: string) => norm(s.replace(TYPE_SUFFIX, ""));
  if (norm(a) === norm(b) || bare(a) === bare(b)) return true;
  /**
   * A misspelling, which is a thing a hand-kept database of two thousand rows
   * has whatever anyone intends. Twenty-two of these were sitting in the
   * collection: Tyrantirar, Mimikiyu, Sigilpyh, Lyanroc, Aegilash, Mabostiff.
   * Every one of them lost its match, and with it its scan, its price, its page
   * and its place in the Pokédex, which is how a Pokémon Bart owns showed as an
   * empty slot.
   *
   * Two edits, and only for a name long enough to survive them: on a short name
   * two edits is most of the word, and Muk and Mew are two apart. That is the
   * line the strict check was drawn at in the first place, and it holds, because
   * the pair this exists to reject is Mew against Mewtwo, which is three.
   *
   * Worth remembering what has already had to be true before this is consulted:
   * the row's number resolved to this card inside the set the row itself names.
   * This is not searching for a name, it is deciding whether a number that
   * already lined up is believable.
   */
  const [x, y] = [bare(a), bare(b)];
  const cap = Math.min(x.length, y.length) >= 6 ? 2 : 1;
  return editDistance(x, y, cap) <= cap;
};

/**
 * Runs `work` over `items` a few at a time. Everything here used to be fired at
 * once, which for a collection this size meant 48 simultaneous set fetches and
 * then a burst of per-card fallbacks on top. TCGdex started refusing them, and
 * a refused set fetch is a whole section of the page with no artwork, so the
 * page was being punished for asking too fast rather than for asking wrongly.
 */
/**
 * Cardmarket's prices for a set of TCGdex card ids.
 *
 * One request per card, because the set endpoint carries only id, image,
 * localId and name: the prices live on the individual card. Measured at eight
 * at a time: the whole collection, sixteen hundred cards, takes about thirteen
 * seconds, and json() caches each for a day, so a revalidation an hour later
 * refetches nothing. Prices move slower than the binder does.
 */
async function pricesFor(ids: string[]): Promise<Map<string, Price>> {
  const out = new Map<string, Price>();
  await mapLimit(ids, 8, async (id) => {
    const card = (await json(`https://api.tcgdex.net/v2/en/cards/${id}`, `card ${id}`)) as {
      pricing?: {
        cardmarket?: { low?: number | null; trend?: number | null; avg30?: number | null };
      };
    } | null;
    const cm = card?.pricing?.cardmarket;
    if (!cm) return;
    const price = priceOf(cm);
    if (price) out.set(id, price);
  });
  return out;
}

async function mapLimit<T, R>(items: T[], limit: number, work: (item: T) => Promise<R>) {
  const out: R[] = new Array(items.length);
  let next = 0;
  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, async () => {
      while (next < items.length) {
        const i = next++;
        out[i] = await work(items[i]!);
      }
    }),
  );
  return out;
}

/**
 * The tag on the Notion query below, shared with app/api/cards/route.ts so the
 * writer and the reader cannot name it differently.
 */
export const CARDS_TAG = "cards-notion";

/**
 * Every row Bart marked as owned. Notion caps a query at 100 rows, so this
 * follows the cursor. The page limit is a backstop against a runaway loop, not
 * a real ceiling: 20 pages is 2000 cards.
 */
async function fetchOwnedRows(token: string): Promise<NotionPage[]> {
  const rows: NotionPage[] = [];
  let cursor: string | undefined;

  for (let page = 0; page < 20; page++) {
    const res = await fetch(`https://api.notion.com/v1/databases/${TRADING_DATABASE}/query`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Notion-Version": NOTION_VERSION,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        // No filter. It used to ask only for Collection = true, which left the
        // wishlist invisible: those rows are the same cards, wanted rather than
        // held, and worth showing as such.
        sorts: [{ timestamp: "created_time", direction: "descending" }],
        page_size: 100,
        ...(cursor ? { start_cursor: cursor } : {}),
      }),
      // A collection changes when a pack is opened, not by the minute. Must be
      // a cached fetch either way: a `no-store` here would turn the page
      // dynamic and make every visitor wait on the whole walk.
      //
      // Tagged, because there is now one thing that knows better than the hour:
      // /api/cards, which has just added a row and revalidates this tag so the
      // card appears on the page it was added from rather than up to an hour
      // later.
      next: { revalidate: 3600, tags: [CARDS_TAG] },
    });
    // Thrown rather than broken out of. A break here returned whatever had been
    // collected so far, which for a refusal on the first page is nothing and for
    // one on the fourth is a truncated binder, and getCards() then remembered
    // either as the answer. Neither is a collection; both are an outage.
    if (!res.ok) throw new Error(`Notion cards query failed: ${res.status}`);

    const body = (await res.json()) as {
      results?: NotionPage[];
      has_more?: boolean;
      next_cursor?: string | null;
    };
    rows.push(...(body.results ?? []));
    if (!body.has_more || !body.next_cursor) break;
    cursor = body.next_cursor;
  }

  return rows;
}

/**
 * The TCGdex sets a Notion set name covers: the set itself, plus any subset
 * whose name extends it.
 *
 * That second part matters more than it sounds. A Sword & Shield set keeps its
 * Trainer Gallery cards (TG01 and up) in a separate set called "<name> Trainer
 * Gallery", and Crown Zenith does the same with its Galarian Gallery. Notion
 * files all of them under the parent set, which is how a collector thinks about
 * it, so matching only the parent left every one of those cards without a scan.
 * Nine sets in this collection were empty for exactly this reason.
 */
function resolveSetIds(notionName: string, sets: TcgSet[]): string[] {
  const wanted = norm(notionName);

  const alias = SET_ALIASES[notionName.trim().toLowerCase()];
  if (alias) return [alias];

  const exact = sets.find((s) => norm(s.name) === wanted);
  const main =
    exact ?? sets.find((s) => norm(s.name).includes(wanted) || wanted.includes(norm(s.name)));
  if (!main) return [];

  // Only extensions of the matched name, so "Evolutions" never drags in
  // "Evolving Skies" and a parent never pulls in an unrelated set.
  const subsets = sets.filter((s) => s.id !== main.id && norm(s.name).startsWith(norm(main.name)));
  return [main.id, ...subsets.map((s) => s.id)];
}

/**
 * One set, with a retry.
 *
 * This used to swallow failures silently, which made a bad situation invisible:
 * a refused fetch costs a whole section its artwork, and on the first live run
 * the sets with a Trainer Gallery came out empty even though the same lookup
 * succeeded every time when run on its own. A single delayed retry recovers the
 * transient refusals, and the log line means the next one is diagnosable from
 * the build output instead of by scraping the deployed page.
 */
async function fetchSet(id: string): Promise<TcgSetDetail | null> {
  try {
    return (await json(`https://api.tcgdex.net/v2/en/sets/${id}`, `set ${id}`)) as TcgSetDetail;
  } catch {
    // Already logged. One missing set costs that section its artwork; the rest
    // of the collection is still worth rendering.
    return null;
  }
}

/**
 * Limitless publishes scans as soon as a set is out, at a path built from the
 * set's printed abbreviation, which is where a card too new for TCGdex comes
 * from. The path is guessed rather than looked up, so the file is checked
 * before it is handed out, and it is served through our own origin because
 * Limitless sends no CORS header.
 *
 * The code is the abbreviation ("SSP"), not the TCGdex id ("sv08"). That was
 * the bug: every guess was built as SV08_088 and quietly 403'd, so a fallback
 * that looked like it was working had in fact never returned a single scan.
 */
async function limitlessScan(code: string, number: string): Promise<string | null> {
  for (const id of numberForms(number)) {
    const guess = `https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/tpci/${code}/${code}_${id}_R_EN_LG.png`;
    try {
      const head = await fetch(guess, { method: "HEAD", next: { revalidate: DAY } });
      if (head.ok) return `/api/cover?url=${encodeURIComponent(guess)}`;
    } catch {
      // try the next form
    }
  }
  return null;
}

/**
 * One walk of the collection per build, shared.
 *
 * The detail route renders 1622 pages and every one of them needs to know which
 * printings Bart holds. The upstream calls are all fetch-cached, so that part is
 * paid once either way, but the Notion paging and the grouping are not: without
 * this they ran 1622 times over. A module-level promise lives for the length of
 * the build (and, on the server, until the process recycles), which is the same
 * window the fetch cache uses.
 */
let collection: Promise<CardSet[]> | null = null;
/** When the memo above was made, for the TTL below. */
let collectedAt = 0;

/**
 * How long that memo is allowed to be the answer.
 *
 * This is not a weakening of the paragraph above, it is the price of /cards
 * being able to add a card. A row written through /api/cards clears the memo in
 * the process that served the write, and there is no reaching the other ones:
 * a warm instance holding a promise from before the write would rebuild the
 * page from the old walk and cache that for an hour, so the card Bart just
 * added would be missing from the page he added it on.
 *
 * Ten minutes bounds that without touching what the memo is for. The build
 * renders all 1622 detail pages in about forty seconds, well inside it, so the
 * walk is still paid once there. A re-walk after that costs one Notion query
 * and finds every upstream call already in the fetch cache.
 */
const MEMO_TTL = 10 * 60 * 1000;

/**
 * Drops the memo, for the one caller that knows it is wrong: the route that has
 * just written a row. See MEMO_TTL for the instances this cannot reach.
 */
export function forgetCollection() {
  collection = null;
}

/**
 * A memo that a failure does not outlive.
 *
 * The subtlety is that the thing being cached is a promise, so a rejected one
 * is cached exactly as happily as a fulfilled one, and every later caller gets
 * the same rejection back without a single request being made. There is a
 * reachable path to that: pricesFor() calls json() with no catch of its own,
 * and json() rethrows once TCGdex has refused three times. One refusal on one
 * price lookup would have taken /cards, all 1622 detail pages, the intercepted
 * modal and the card sitemap down together, and kept them down until the lambda
 * recycled, which is not a thing a price is allowed to do.
 *
 * So the slot is cleared on the way past. The next render walks again, pays for
 * one Notion query, and finds the rest of the work already in the fetch cache.
 * The empty array is the same fail-soft answer the rest of the module gives.
 */
export function getCards(): Promise<CardSet[]> {
  if (collection && Date.now() - collectedAt > MEMO_TTL) collection = null;
  if (!collection) {
    collectedAt = Date.now();
    collection = walkCollection().catch((err) => {
      collection = null;
      console.error("Card collection walk failed, retrying on the next render:", err);
      return [];
    });
  }
  return collection;
}

/**
 * The same collection with every price taken out.
 *
 * This is what makes the public link honest rather than decorative. Hiding a
 * price in the interface leaves it in the props React ships to the browser, in
 * the HTML of a server-rendered page, and in view for anyone who opens the
 * developer tools. Removing it here means the number never leaves the server:
 * /user/<name> renders from this, and there is nothing to find.
 *
 * `price` is already nullable, because plenty of cards have no Cardmarket
 * entry, so nothing downstream needs a new branch. Every place that shows money
 * is already written as `card.price && …` for that reason, and all of them go
 * quiet on their own.
 *
 * Only `price` needs clearing: the raw Cardmarket figures live on `CardDetail`,
 * which the public page does not build. If a `market` field ever moves onto
 * `OwnedCard`, it has to be cleared here too.
 *
 * A new array rather than a mutation: `getCards()` hands out a memoised object
 * that the owner's page is also holding, and editing it in place would empty
 * the prices out of /cards for as long as the process lived.
 */
export function stripPrices(sets: CardSet[]): CardSet[] {
  return sets.map((set) => ({
    ...set,
    cards: set.cards.map((card) => ({ ...card, price: null })),
  }));
}

async function walkCollection(): Promise<CardSet[]> {
  const token = process.env.NOTION_TOKEN;
  // Not a failure, and the one empty worth remembering: a deployment either has
  // the token or it does not, and it will not acquire one mid-process.
  if (!token) return [];

  // Deliberately uncaught. It used to return [] here, which looked like the
  // fail-soft convention and was in fact the same trap as above wearing it:
  // an outage during one revalidation was memoised as "Bart owns no cards" for
  // as long as the process lived. Thrown, it reaches getCards(), which clears
  // the slot, so the empty page lasts one render instead of all of them.
  const rows = await fetchOwnedRows(token);
  if (!rows.length) return [];

  // Group first, so each set is only resolved once however many cards came from
  // it. Unlike the hobbies card this ignores a cover set by hand in Notion:
  // those come back as presigned S3 URLs on a host the CSP does not allow, so
  // across a whole grid they would be a wall of blocked images rather than the
  // one Bart picked. TCGdex and Limitless are both allowed (see next.config.ts).
  const grouped = new Map<string, Record<string, NotionProperty>[]>();
  for (const row of rows) {
    const props = row.properties ?? {};
    const setName = props.Set?.select?.name;
    if (!setName || !text(props.Name)) continue;
    const bucket = grouped.get(setName) ?? [];
    bucket.push(props);
    grouped.set(setName, bucket);
  }
  if (!grouped.size) return [];

  // The single point of failure for every scan on the page: without the index
  // no set name can be resolved, so one refused request here is the difference
  // between a binder and a wall of empty slots. Hence the retries in json(),
  // and hence the loud log if it still gives up.
  let sets: TcgSet[] = [];
  try {
    sets = (await json("https://api.tcgdex.net/v2/en/sets", "sets index")) as TcgSet[];
  } catch {
    console.error("No TCGdex set index: /cards will render without any artwork.");
  }

  // Three at a time, and the subsets of a set in turn rather than alongside it.
  // Forty-eight sets going at once was enough for TCGdex to start refusing, and
  // a refusal here is a whole section of the page with no artwork.
  const out = await mapLimit([...grouped.entries()], 3, async ([setName, entryProps]) => {
    const ids = sets.length ? resolveSetIds(setName, sets) : [];
    const details = (await mapLimit(ids, 1, fetchSet)).filter(Boolean) as TcgSetDetail[];
    // The first is the set itself; the rest are its galleries, which have their
    // own logos and dates and should not be the ones on the heading.
    const detail = details[0] ?? null;

    // Where this set keeps its artwork, taken off the logo it already handed
    // over rather than guessed: ".../en/swsh/swsh12.5/logo" minus the logo.
    //
    // The gallery subsets need it. TCGdex lists their cards with an id, a
    // localId and a name and no image at all, so a Galarian Gallery card
    // matched perfectly and then had nothing to build a URL from: Crown Zenith
    // rendered one scan out of 58. The files do exist, filed under the parent
    // set rather than the subset (swsh12.5/GG69, not swsh12.5gg/GG69, which is
    // a 404), and the same holds for every Trainer Gallery.
    const assetBase = detail?.logo?.replace(/\/logo$/, "") ?? null;

    // localId is the number as TCGdex writes it, so index every form of it once
    // and the per-card match becomes a lookup instead of a scan. Subsets are
    // folded into the same index: TG01 simply is not in the parent set.
    const byNumber = new Map<string, TcgCard>();
    for (const d of details) {
      for (const card of d.cards ?? []) {
        if (!card.localId) continue;
        for (const form of numberForms(card.localId)) {
          if (!byNumber.has(form)) byNumber.set(form, card);
        }
      }
    }
    // Second pass, on the numeric tail of a prefixed id. Promo sets number their
    // cards "XY74" or "SWSH001" while Notion writes the bare "74", so without
    // this every promo in the collection is unmatched. It runs after the exact
    // forms and never overwrites them, which is what keeps a set's own card 01
    // ahead of its Trainer Gallery's TG01.
    for (const d of details) {
      for (const card of d.cards ?? []) {
        const tail = card.localId?.match(/^[A-Za-z]+(\d+[A-Za-z]?)$/)?.[1];
        if (!tail) continue;
        for (const form of numberForms(tail)) {
          if (!byNumber.has(form)) byNumber.set(form, card);
        }
      }
    }

    // Only the parent set has a printed abbreviation worth guessing with. The
    // galleries carry theirs as "ASR:TG", which is not a path segment, and
    // Limitless files those cards under the parent's numbering instead. Working
    // out that offset would mean guessing, and an off-by-one there shows a
    // confidently wrong card, so gallery cards TCGdex has no scan for keep
    // their empty slot.
    const code = detail?.abbreviation?.official?.split(":")[0]?.toUpperCase() ?? null;

    // The fallback is one to three HEAD requests per card, so on a set TCGdex
    // does not know at all it would fire hundreds and find nothing. A cap keeps
    // it useful for the handful of cards from a set too new to be indexed,
    // which is the only case it was ever for.
    let fallbacks = 40;

    /**
     * Does this set have scans at all?
     *
     * TCGdex publishes the record before the artwork, and it does not say so:
     * every card in a set that has just been announced still carries an `image`
     * URL, and every one of those URLs is a 404. Pitch Black is 120 of them.
     *
     * The browser used to find that out the hard way, one card at a time, and
     * the 404 of a missing scan carries no cache-control, so each attempt
     * travelled all the way back to origin. That is what made a new set take
     * seconds to fail to paint.
     *
     * One HEAD, here, decides it for the whole set. The answer is cached for a
     * day like everything else, and a set that has no scans hands out nulls, so
     * the grid draws its empty slots immediately instead of discovering them.
     */
    const probe = details.flatMap((d) => d.cards ?? []).find((c) => c.image)?.image;
    let setHasScans = true;
    if (probe) {
      try {
        const res = await fetch(`${probe}/low.webp`, {
          method: "HEAD",
          next: { revalidate: DAY },
        });
        setHasScans = res.ok;
      } catch {
        // A probe that cannot be made is not proof of absence: assume the scans
        // are there and let the per-card fallback do what it always did.
        setHasScans = true;
      }
    }

    // One entry per printing first, then folded together below. Splitting it
    // this way keeps the artwork lookup running eight at a time over the rows
    // as they came from Notion, rather than over an already-grouped structure.
    const printings = await mapLimit(entryProps, 8, async (props) => {
      const name = text(props.Name);
      const number = text(props.Number);
      const match = numberForms(number)
        .map((form) => byNumber.get(form))
        .find(Boolean);
      // A number that resolves to a different Pokémon means the numbering does
      // not line up, and a wrong scan is worse than a missing one.
      const matched = match?.name && !sameCard(match.name, name) ? undefined : match;

      // low, not high. TCGdex publishes both; high is around 600px wide and
      // 77kB, low is 245px and 22kB. The grid draws these at 104 to 132px and
      // the list view at 44px, and there is no detail view anywhere on the
      // route, so every one of those 55 extra kilobytes was decoded and thrown
      // away. It is the page's LCP element, measured at seven seconds on a
      // throttled phone.
      //
      // Through localise(), which is the identity function here (see ./util). This was the
      // one place that skipped it: scripts/localise-images.mjs had already
      // pulled 1,449 of these scans into public/artwork/cards, the manifest
      // mapped every one of them, and nothing read it. Every card on the page
      // was still being fetched from TCGdex' CDN, which is why the sets that
      // happen to sit on a cold edge there load visibly slower than the rest.
      //
      // The size the grid draws at is a slider now, and past about 180px the
      // 245px file is being stretched. So the big one is resolved too and
      // handed over beside the small one, for the browser to ask for only if
      // the reader ever pushes the grid up that far. Only from TCGdex, whose
      // URLs carry the size as the last segment: the two fallbacks below
      // publish one file each and there is no larger one to name.
      const tcgBase = !setHasScans
        ? null
        : (matched?.image ??
          (matched?.localId && assetBase ? `${assetBase}/${matched.localId}` : null));
      let image = tcgBase ? localise(`${tcgBase}/low.webp`) : null;
      let imageHigh = tcgBase ? localise(`${tcgBase}/high.webp`) : null;
      // Skip the gallery numbers: their scans are not under this code.
      if (!image && number && !/^[A-Za-z]/.test(number) && fallbacks > 0) {
        fallbacks--;
        // Limitless first, where the set has a code there. Not every set does,
        // and the second catalogue does not need one: it is asked by set name.
        if (code) image = await limitlessScan(code, number);
        // The last resort, for the cards neither TCGdex nor Limitless has. This
        // is the one that finds the €440 Pikachu with the grey felt hat, the
        // most expensive card in the binder and the only one on the dashboard
        // with an empty square where its picture goes.
        image ??= await ptcgScan(setName, number);
        // A fallback scan is one file, so there is no larger version of it to
        // offer and the grid keeps drawing the one it has.
        imageHigh = null;
      }

      return {
        key: `${setName}-${number || name}`,
        name,
        number,
        type: fieldOf(props, /^type/i),
        gen: fieldOf(props, /^gen/i),
        image,
        imageHigh,
        imageSize: measure(image),
        // TCGdex' name where the row matched one, the row's own where it did
        // not. Which Pokémon a card shows is a fact about the card rather than
        // about how it was typed, and the Dex is the one place a misspelling
        // was silently destructive: "Tyrantirar" is not a species, so the card
        // simply was not filed anywhere and Tyranitar read as uncaught. The
        // scans and the prices survive a typo now (see sameCard); this is the
        // rest of that.
        speciesId: speciesOf(matched?.name ?? name),
        // Kept only long enough to look the price up below: it is TCGdex's id
        // for this card, and the price endpoint is the only thing that wants it.
        tcgId: matched?.id ?? null,
        rarity: fieldOf(props, /rarit/i),
        owned: props.Collection?.checkbox !== false,
      };
    });

    // One pass over the whole set rather than a request inside the map above:
    // that map already runs eight at a time, and a nested fetch would have made
    // it eight times eight.
    const prices = await pricesFor([
      ...new Set(printings.map((p) => p.tcgId).filter(Boolean)),
    ] as string[]);

    // Holding a card normally and again as a reverse holo is one card with two
    // printings, not two cards. 317 of them in this collection, and shown twice
    // they read as a duplicate rather than as something worth knowing. The
    // rarities become tags under a single scan.
    const merged = new Map<string, OwnedCard>();
    for (const p of printings) {
      const existing = merged.get(p.key);
      const variant = { rarity: p.rarity, owned: p.owned };
      if (existing) {
        // Notion can hold the same rarity twice; the tag only needs saying once.
        if (
          !existing.variants.some((v) => v.rarity === variant.rarity && v.owned === variant.owned)
        )
          existing.variants.push(variant);
        existing.owned ||= p.owned;
        // The first row of a card may be the one with no artwork, and the same
        // goes for the price: a card held twice is one card, and whichever of
        // its rows TCGdex matched is the one that knows what it is worth.
        existing.image ??= p.image;
        existing.price ??= (p.tcgId && prices.get(p.tcgId)) || null;
        existing.tcgId ??= p.tcgId;
        continue;
      }
      merged.set(p.key, {
        key: p.key,
        name: p.name,
        number: p.number,
        type: p.type,
        gen: p.gen,
        image: p.image,
        imageHigh: p.imageHigh,
        imageSize: p.imageSize,
        speciesId: p.speciesId,
        price: (p.tcgId && prices.get(p.tcgId)) || null,
        tcgId: p.tcgId,
        variants: [variant],
        owned: p.owned,
      });
    }
    const cards = [...merged.values()];
    const setLogo = await setArt(setName, detail);

    return {
      name: setName,
      logo: setLogo,
      logoSize: measure(setLogo),
      releaseDate: detail?.releaseDate ?? null,
      total: detail?.cardCount?.official ?? detail?.cardCount?.total ?? null,
      // Ascending by number, which is the order the cards sit in a binder. The
      // gallery cards are lettered (TG01), so they sort to the front on a
      // numeric parse of 0; comparing the raw string keeps them together at
      // the end where a collector expects them.
      cards: cards.sort((a, b) => {
        const na = parseInt(a.number, 10);
        const nb = parseInt(b.number, 10);
        if (Number.isNaN(na) || Number.isNaN(nb)) return a.number.localeCompare(b.number, LOCALE);
        return na - nb;
      }),
    };
  });

  // Newest set first. A set TCGdex has never heard of has no date to sort on
  // and goes last rather than jumping to the front on an empty string.
  return out.sort((a, b) => (b.releaseDate ?? "").localeCompare(a.releaseDate ?? "", LOCALE));
}

/**
 * The black star every promo set wears, which TCGdex publishes once, under the
 * Sword & Shield promos. It is not that set's branding: it is the mark printed
 * on the cards themselves, and it is the same on all of them.
 */
const PROMO_STAR = "https://assets.tcgdex.net/en/swsh/swshp/logo.webp";

/**
 * What to show for a set, in the order of how much it says.
 *
 * Not every set has a logo. TCGdex has none for Temporal Forces or for either
 * of the two recent Black Star Promos sets, and a set with no art was a grey
 * box in the rail, which reads as something that failed to load rather than as
 * something that was never published. So: the logo, then the promo star for the
 * promo sets, then the set symbol, then honestly nothing.
 */
async function setArt(name: string, detail: TcgSetDetail | null | undefined) {
  if (detail?.logo) return localise(`${detail.logo}.webp`);
  if (/black star promos/i.test(name)) return localise(PROMO_STAR);
  // Their logo before TCGdex's symbol: the symbol for a set with no logo is a
  // 25px box with the set's three-letter code in it, which in a rail of
  // wordmarks reads as a placeholder rather than as a set.
  const theirs = await ptcgLogo(name);
  if (theirs) return localise(theirs);
  if (detail?.symbol) return localise(`${detail.symbol}.webp`);
  return null;
}

/**
 * Where a card is on Cardmarket.
 *
 * The straight answer is its own product page, and the path to it is generated
 * by scripts/cardmarket-links.mjs: their catalogue names the product, the header
 * of that script says how the two halves of the URL are built and why the
 * expansion half has to be checked by hand.
 *
 * The fallback is a search on the card's name, and the important part of it is
 * what is *not* in the query. It used to be name plus set name, which found
 * nothing at all: a product there is called "Alakazam [Damage Swap | Confuse
 * Ray]", so the set name matches no product on the site and every search came
 * back empty. The name alone is broad but it is never empty.
 *
 * language=1&minCondition=2 is English, Near Mint or better, which is the exact
 * copy the price beside this link is an estimate for (see NM_BANDS in
 * price-basis.mjs). Without it their page opens on every condition in every
 * language and the cheapest listing on screen is a played Japanese one.
 */
function cardmarketUrl(id: string, name: string): string {
  const path = (LINKS as Record<string, string | undefined>)[id];
  return path
    ? `https://www.cardmarket.com/en/Pokemon/Products/Singles/${path}?language=1&minCondition=2`
    : `https://www.cardmarket.com/en/Pokemon/Products/Search?searchString=${encodeURIComponent(name)}`;
}

/** Everything TCGdex knows about one card, for the detail route. */
export type CardDetail = {
  id: string;
  name: string;
  image: string | null;
  rarity: string | null;
  illustrator: string | null;
  hp: number | null;
  types: string[];
  stage: string | null;
  evolveFrom: string | null;
  regulationMark: string | null;
  set: { id: string; name: string; logo: string | null; total: number | null } | null;
  /** Cardmarket's product id, which is how a card is addressed on their site. */
  cmId: number | null;
  /** Where to buy it. See cardmarketUrl. */
  cmUrl: string;
  price: Price | null;
  /** The rest of Cardmarket's numbers, for the card's own page. */
  market: { avg: number | null; trend: number | null; avg7: number | null } | null;
};

/**
 * One card, in full, from TCGdex.
 *
 * Separate from getCards() on purpose: the list needs eight fields per card and
 * pays for them once per set, and the detail page needs everything for exactly
 * one card. Fetching the set to render a single card would be the wrong shape.
 *
 * Fails soft like the rest: a card TCGdex does not have, or an outage, returns
 * null and the route 404s rather than rendering an empty frame.
 */
export async function getCardDetail(id: string): Promise<CardDetail | null> {
  let card;
  try {
    card = (await json(`https://api.tcgdex.net/v2/en/cards/${id}`, `card ${id}`)) as {
      id?: string;
      name?: string;
      image?: string;
      rarity?: string;
      illustrator?: string;
      hp?: number;
      types?: string[];
      stage?: string;
      evolveFrom?: string;
      regulationMark?: string;
      set?: { id?: string; name?: string; logo?: string; cardCount?: { total?: number } };
      pricing?: {
        cardmarket?: {
          idProduct?: number;
          low?: number | null;
          avg30?: number | null;
          avg?: number | null;
          trend?: number | null;
          avg7?: number | null;
        };
      };
    } | null;
  } catch {
    return null;
  }
  if (!card?.id || !card.name) return null;
  const cm = card.pricing?.cardmarket;
  return {
    id: card.id,
    name: card.name,
    image: card.image ?? null,
    rarity: card.rarity ?? null,
    illustrator: card.illustrator ?? null,
    hp: num(card.hp),
    types: card.types ?? [],
    stage: card.stage ?? null,
    evolveFrom: card.evolveFrom ?? null,
    regulationMark: card.regulationMark ?? null,
    set: card.set?.id
      ? {
          id: card.set.id,
          name: card.set.name ?? card.set.id,
          logo: card.set.logo ? `${card.set.logo}.webp` : null,
          total: num(card.set.cardCount?.total),
        }
      : null,
    cmId: num(cm?.idProduct),
    cmUrl: cardmarketUrl(card.id, card.name),
    price: cm ? priceOf(cm) : null,
    market: cm ? { avg: num(cm.avg), trend: num(cm.trend), avg7: num(cm.avg7) } : null,
  };
}
