/**
 * Corrections to TCGdex's facts about English cards, applied where the catalogue reads them
 * (englishFacts in tcgdex-browse.ts), so the nightly copy, set pages, search and the collection
 * all carry them.
 *
 * Found on 2026-09-14 by laying all 21,068 English cards beside TCGplayer's products (tcgcsv, every
 * group) through the product links:
 *
 * - **rarity "None"**: TCGdex writes the word for 499 cards (trainer kits, McDonald's collections,
 *   Pokémon Rumble, Kalos Starter Set and more). TCGplayer names 460 of them; its
 *   "Unconfirmed" (all of My First Battle) is not a rarity and is left alone.
 * - **types missing**: 16 Pokémon with none at all (Best of Game, Pokémon Futsal 2020, Morpeko
 *   V-UNION), filled from TCGplayer's Card Type.
 * - **types wrong**: 29 cards disagreed; pokemontcg.io broke the tie. Five times TCGdex was
 *   outvoted (Drampa, Quagsire, Hariyama, Sandshrew, Dark Houndoom), and those are here. The
 *   others were TCGplayer's error or a wrong product link (fixed in #410) and stay as TCGdex has
 *   them.
 *
 * Each entry is [what TCGdex says, what the card is]. It applies only while TCGdex still says the
 * first, so a fix upstream wins and a stale entry does nothing.
 */
export type FactCorrection = {
  rarity?: [string, string];
  types?: [string[], string[]];
};

export const CARD_FACT_CORRECTIONS: Readonly<Record<string, FactCorrection>> = {
  "2011bw-1": { rarity: ["None", "Promo"] },
  "2011bw-10": { rarity: ["None", "Promo"] },
  "2011bw-11": { rarity: ["None", "Promo"] },
  "2011bw-12": { rarity: ["None", "Promo"] },
  "2011bw-2": { rarity: ["None", "Promo"] },
  "2011bw-3": { rarity: ["None", "Promo"] },
  "2011bw-4": { rarity: ["None", "Promo"] },
  "2011bw-5": { rarity: ["None", "Promo"] },
  "2011bw-6": { rarity: ["None", "Promo"] },
  "2011bw-7": { rarity: ["None", "Promo"] },
  "2011bw-8": { rarity: ["None", "Promo"] },
  "2011bw-9": { rarity: ["None", "Promo"] },
  "2012bw-1": { rarity: ["None", "Promo"] },
  "2012bw-10": { rarity: ["None", "Promo"] },
  "2012bw-11": { rarity: ["None", "Promo"] },
  "2012bw-12": { rarity: ["None", "Promo"] },
  "2012bw-2": { rarity: ["None", "Promo"] },
  "2012bw-3": { rarity: ["None", "Promo"] },
  "2012bw-4": { rarity: ["None", "Promo"] },
  "2012bw-5": { rarity: ["None", "Promo"] },
  "2012bw-6": { rarity: ["None", "Promo"] },
  "2012bw-7": { rarity: ["None", "Promo"] },
  "2012bw-8": { rarity: ["None", "Promo"] },
  "2012bw-9": { rarity: ["None", "Promo"] },
  "2014xy-1": { rarity: ["None", "Promo"] },
  "2014xy-10": { rarity: ["None", "Promo"] },
  "2014xy-11": { rarity: ["None", "Promo"] },
  "2014xy-12": { rarity: ["None", "Promo"] },
  "2014xy-2": { rarity: ["None", "Promo"] },
  "2014xy-3": { rarity: ["None", "Promo"] },
  "2014xy-4": { rarity: ["None", "Promo"] },
  "2014xy-5": { rarity: ["None", "Promo"] },
  "2014xy-6": { rarity: ["None", "Promo"] },
  "2014xy-7": { rarity: ["None", "Promo"] },
  "2014xy-8": { rarity: ["None", "Promo"] },
  "2014xy-9": { rarity: ["None", "Promo"] },
  "2015xy-1": { rarity: ["None", "Promo"] },
  "2015xy-10": { rarity: ["None", "Promo"] },
  "2015xy-11": { rarity: ["None", "Promo"] },
  "2015xy-12": { rarity: ["None", "Promo"] },
  "2015xy-2": { rarity: ["None", "Promo"] },
  "2015xy-3": { rarity: ["None", "Promo"] },
  "2015xy-4": { rarity: ["None", "Promo"] },
  "2015xy-5": { rarity: ["None", "Promo"] },
  "2015xy-6": { rarity: ["None", "Promo"] },
  "2015xy-7": { rarity: ["None", "Promo"] },
  "2015xy-8": { rarity: ["None", "Promo"] },
  "2015xy-9": { rarity: ["None", "Promo"] },
  "2016xy-1": { rarity: ["None", "Promo"] },
  "2016xy-10": { rarity: ["None", "Promo"] },
  "2016xy-11": { rarity: ["None", "Promo"] },
  "2016xy-12": { rarity: ["None", "Promo"] },
  "2016xy-2": { rarity: ["None", "Promo"] },
  "2016xy-3": { rarity: ["None", "Promo"] },
  "2016xy-4": { rarity: ["None", "Promo"] },
  "2016xy-5": { rarity: ["None", "Promo"] },
  "2016xy-6": { rarity: ["None", "Promo"] },
  "2016xy-7": { rarity: ["None", "Promo"] },
  "2016xy-8": { rarity: ["None", "Promo"] },
  "2016xy-9": { rarity: ["None", "Promo"] },
  "2017sm-1": { rarity: ["None", "Promo"] },
  "2017sm-10": { rarity: ["None", "Promo"] },
  "2017sm-11": { rarity: ["None", "Promo"] },
  "2017sm-12": { rarity: ["None", "Promo"] },
  "2017sm-2": { rarity: ["None", "Promo"] },
  "2017sm-3": { rarity: ["None", "Promo"] },
  "2017sm-4": { rarity: ["None", "Promo"] },
  "2017sm-5": { rarity: ["None", "Promo"] },
  "2017sm-6": { rarity: ["None", "Promo"] },
  "2017sm-7": { rarity: ["None", "Promo"] },
  "2017sm-8": { rarity: ["None", "Promo"] },
  "2017sm-9": { rarity: ["None", "Promo"] },
  "2018sm-1": { rarity: ["None", "Promo"] },
  "2018sm-10": { rarity: ["None", "Promo"] },
  "2018sm-11": { rarity: ["None", "Promo"] },
  "2018sm-12": { rarity: ["None", "Promo"] },
  "2018sm-2": { rarity: ["None", "Promo"] },
  "2018sm-3": { rarity: ["None", "Promo"] },
  "2018sm-4": { rarity: ["None", "Promo"] },
  "2018sm-5": { rarity: ["None", "Promo"] },
  "2018sm-6": { rarity: ["None", "Promo"] },
  "2018sm-7": { rarity: ["None", "Promo"] },
  "2018sm-8": { rarity: ["None", "Promo"] },
  "2018sm-9": { rarity: ["None", "Promo"] },
  "2019sm-1": { rarity: ["None", "Promo"] },
  "2019sm-10": { rarity: ["None", "Promo"] },
  "2019sm-11": { rarity: ["None", "Promo"] },
  "2019sm-12": { rarity: ["None", "Promo"] },
  "2019sm-2": { rarity: ["None", "Promo"] },
  "2019sm-3": { rarity: ["None", "Promo"] },
  "2019sm-4": { rarity: ["None", "Promo"] },
  "2019sm-5": { rarity: ["None", "Promo"] },
  "2019sm-6": { rarity: ["None", "Promo"] },
  "2019sm-7": { rarity: ["None", "Promo"] },
  "2019sm-8": { rarity: ["None", "Promo"] },
  "2019sm-9": { rarity: ["None", "Promo"] },
  "2021swsh-1": { rarity: ["None", "Promo"] },
  "2021swsh-10": { rarity: ["None", "Promo"] },
  "2021swsh-11": { rarity: ["None", "Promo"] },
  "2021swsh-12": { rarity: ["None", "Promo"] },
  "2021swsh-13": { rarity: ["None", "Promo"] },
  "2021swsh-14": { rarity: ["None", "Promo"] },
  "2021swsh-15": { rarity: ["None", "Promo"] },
  "2021swsh-16": { rarity: ["None", "Promo"] },
  "2021swsh-17": { rarity: ["None", "Promo"] },
  "2021swsh-18": { rarity: ["None", "Promo"] },
  "2021swsh-19": { rarity: ["None", "Promo"] },
  "2021swsh-2": { rarity: ["None", "Promo"] },
  "2021swsh-20": { rarity: ["None", "Promo"] },
  "2021swsh-21": { rarity: ["None", "Promo"] },
  "2021swsh-22": { rarity: ["None", "Promo"] },
  "2021swsh-23": { rarity: ["None", "Promo"] },
  "2021swsh-24": { rarity: ["None", "Promo"] },
  "2021swsh-25": { rarity: ["None", "Promo"] },
  "2021swsh-3": { rarity: ["None", "Promo"] },
  "2021swsh-4": { rarity: ["None", "Promo"] },
  "2021swsh-5": { rarity: ["None", "Promo"] },
  "2021swsh-6": { rarity: ["None", "Promo"] },
  "2021swsh-7": { rarity: ["None", "Promo"] },
  "2021swsh-8": { rarity: ["None", "Promo"] },
  "2021swsh-9": { rarity: ["None", "Promo"] },
  "2022swsh-1": { rarity: ["None", "Promo"] },
  "2022swsh-10": { rarity: ["None", "Promo"] },
  "2022swsh-11": { rarity: ["None", "Promo"] },
  "2022swsh-12": { rarity: ["None", "Promo"] },
  "2022swsh-13": { rarity: ["None", "Promo"] },
  "2022swsh-14": { rarity: ["None", "Promo"], types: [["Colorless"], ["Dragon"]] },
  "2022swsh-15": { rarity: ["None", "Promo"] },
  "2022swsh-2": { rarity: ["None", "Promo"] },
  "2022swsh-3": { rarity: ["None", "Promo"] },
  "2022swsh-4": { rarity: ["None", "Promo"] },
  "2022swsh-5": { rarity: ["None", "Promo"] },
  "2022swsh-6": { rarity: ["None", "Promo"] },
  "2022swsh-7": { rarity: ["None", "Promo"] },
  "2022swsh-8": { rarity: ["None", "Promo"] },
  "2022swsh-9": { rarity: ["None", "Promo"] },
  "2023sv-1": { rarity: ["None", "Promo"] },
  "2023sv-10": { rarity: ["None", "Promo"] },
  "2023sv-11": { rarity: ["None", "Promo"] },
  "2023sv-12": { rarity: ["None", "Promo"] },
  "2023sv-13": { rarity: ["None", "Promo"] },
  "2023sv-14": { rarity: ["None", "Promo"] },
  "2023sv-15": { rarity: ["None", "Promo"] },
  "2023sv-2": { rarity: ["None", "Promo"] },
  "2023sv-3": { rarity: ["None", "Promo"] },
  "2023sv-4": { rarity: ["None", "Promo"] },
  "2023sv-5": { rarity: ["None", "Promo"] },
  "2023sv-6": { rarity: ["None", "Promo"] },
  "2023sv-7": { rarity: ["None", "Promo"] },
  "2023sv-8": { rarity: ["None", "Promo"] },
  "2023sv-9": { rarity: ["None", "Promo"] },
  "2024sv-1": { rarity: ["None", "Promo"] },
  "2024sv-10": { rarity: ["None", "Promo"] },
  "2024sv-11": { rarity: ["None", "Promo"] },
  "2024sv-12": { rarity: ["None", "Promo"] },
  "2024sv-13": { rarity: ["None", "Promo"] },
  "2024sv-14": { rarity: ["None", "Promo"] },
  "2024sv-15": { rarity: ["None", "Promo"] },
  "2024sv-2": { rarity: ["None", "Promo"] },
  "2024sv-3": { rarity: ["None", "Promo"] },
  "2024sv-4": { rarity: ["None", "Promo"] },
  "2024sv-5": { rarity: ["None", "Promo"] },
  "2024sv-6": { rarity: ["None", "Promo"] },
  "2024sv-7": { rarity: ["None", "Promo"] },
  "2024sv-8": { rarity: ["None", "Promo"] },
  "2024sv-9": { rarity: ["None", "Promo"] },
  "bog-1": { rarity: ["None", "Promo"] },
  "bog-2": { rarity: ["None", "Promo"], types: [[], ["Fighting"]] },
  "bog-3": { rarity: ["None", "Promo"] },
  "bog-4": { rarity: ["None", "Promo"], types: [[], ["Metal"]] },
  "bog-5": { rarity: ["None", "Promo"], types: [[], ["Darkness"]] },
  "bog-6": { rarity: ["None", "Promo"], types: [[], ["Grass"]] },
  "bog-7": { rarity: ["None", "Promo"], types: [[], ["Grass"]] },
  "bog-8": { rarity: ["None", "Promo"], types: [[], ["Psychic"]] },
  "bog-9": { rarity: ["None", "Promo"], types: [[], ["Fighting"]] },
  "ex10-44": { types: [["Fire"], ["Fighting"]] },
  "ex11-44": { types: [["Fire"], ["Fighting"]] },
  "ex11-82": { types: [["Water"], ["Fighting"]] },
  "ex7-5": { types: [["Darkness"], ["Fire", "Darkness"]] },
  "fut2020-1": { rarity: ["None", "Promo"], types: [[], ["Lightning"]] },
  "fut2020-2": { rarity: ["None", "Promo"], types: [[], ["Colorless"]] },
  "fut2020-3": { rarity: ["None", "Promo"], types: [[], ["Grass"]] },
  "fut2020-4": { rarity: ["None", "Promo"], types: [[], ["Fire"]] },
  "fut2020-5": { rarity: ["None", "Promo"], types: [[], ["Water"]] },
  "ru1-1": { rarity: ["None", "Promo"] },
  "ru1-10": { rarity: ["None", "Promo"] },
  "ru1-11": { rarity: ["None", "Promo"] },
  "ru1-12": { rarity: ["None", "Promo"] },
  "ru1-13": { rarity: ["None", "Promo"] },
  "ru1-14": { rarity: ["None", "Promo"] },
  "ru1-15": { rarity: ["None", "Promo"] },
  "ru1-16": { rarity: ["None", "Promo"] },
  "ru1-2": { rarity: ["None", "Promo"] },
  "ru1-3": { rarity: ["None", "Promo"] },
  "ru1-4": { rarity: ["None", "Promo"] },
  "ru1-5": { rarity: ["None", "Promo"] },
  "ru1-6": { rarity: ["None", "Promo"] },
  "ru1-7": { rarity: ["None", "Promo"] },
  "ru1-8": { rarity: ["None", "Promo"] },
  "ru1-9": { rarity: ["None", "Promo"] },
  "swshp-SWSH215": { types: [[], ["Lightning"]] },
  "swshp-SWSH216": { types: [[], ["Lightning"]] },
  "swshp-SWSH217": { types: [[], ["Lightning"]] },
  "swshp-SWSH218": { types: [[], ["Lightning"]] },
  "tk-bw-e-1": { rarity: ["None", "Common"] },
  "tk-bw-e-10": { rarity: ["None", "Common"] },
  "tk-bw-e-11": { rarity: ["None", "Common"] },
  "tk-bw-e-12": { rarity: ["None", "Common"] },
  "tk-bw-e-13": { rarity: ["None", "Common"] },
  "tk-bw-e-14": { rarity: ["None", "Common"] },
  "tk-bw-e-15": { rarity: ["None", "Common"] },
  "tk-bw-e-16": { rarity: ["None", "Common"] },
  "tk-bw-e-17": { rarity: ["None", "Common"] },
  "tk-bw-e-18": { rarity: ["None", "Common"] },
  "tk-bw-e-19": { rarity: ["None", "Common"] },
  "tk-bw-e-2": { rarity: ["None", "Common"] },
  "tk-bw-e-20": { rarity: ["None", "Common"] },
  "tk-bw-e-21": { rarity: ["None", "Common"] },
  "tk-bw-e-22": { rarity: ["None", "Common"] },
  "tk-bw-e-23": { rarity: ["None", "Common"] },
  "tk-bw-e-24": { rarity: ["None", "Common"] },
  "tk-bw-e-25": { rarity: ["None", "Common"] },
  "tk-bw-e-26": { rarity: ["None", "Common"] },
  "tk-bw-e-27": { rarity: ["None", "Common"] },
  "tk-bw-e-28": { rarity: ["None", "Common"] },
  "tk-bw-e-29": { rarity: ["None", "Common"] },
  "tk-bw-e-3": { rarity: ["None", "Common"] },
  "tk-bw-e-30": { rarity: ["None", "Common"] },
  "tk-bw-e-4": { rarity: ["None", "Common"] },
  "tk-bw-e-5": { rarity: ["None", "Common"] },
  "tk-bw-e-6": { rarity: ["None", "Common"] },
  "tk-bw-e-7": { rarity: ["None", "Common"] },
  "tk-bw-e-8": { rarity: ["None", "Common"] },
  "tk-bw-e-9": { rarity: ["None", "Common"] },
  "tk-bw-z-1": { rarity: ["None", "Common"] },
  "tk-bw-z-10": { rarity: ["None", "Common"] },
  "tk-bw-z-11": { rarity: ["None", "Common"] },
  "tk-bw-z-12": { rarity: ["None", "Common"] },
  "tk-bw-z-13": { rarity: ["None", "Common"] },
  "tk-bw-z-14": { rarity: ["None", "Common"] },
  "tk-bw-z-15": { rarity: ["None", "Common"] },
  "tk-bw-z-16": { rarity: ["None", "Common"] },
  "tk-bw-z-17": { rarity: ["None", "Common"] },
  "tk-bw-z-18": { rarity: ["None", "Common"] },
  "tk-bw-z-19": { rarity: ["None", "Common"] },
  "tk-bw-z-2": { rarity: ["None", "Common"] },
  "tk-bw-z-20": { rarity: ["None", "Common"] },
  "tk-bw-z-21": { rarity: ["None", "Common"] },
  "tk-bw-z-22": { rarity: ["None", "Common"] },
  "tk-bw-z-23": { rarity: ["None", "Common"] },
  "tk-bw-z-24": { rarity: ["None", "Common"] },
  "tk-bw-z-25": { rarity: ["None", "Common"] },
  "tk-bw-z-26": { rarity: ["None", "Common"] },
  "tk-bw-z-27": { rarity: ["None", "Common"] },
  "tk-bw-z-28": { rarity: ["None", "Common"] },
  "tk-bw-z-29": { rarity: ["None", "Common"] },
  "tk-bw-z-3": { rarity: ["None", "Common"] },
  "tk-bw-z-30": { rarity: ["None", "Common"] },
  "tk-bw-z-4": { rarity: ["None", "Common"] },
  "tk-bw-z-5": { rarity: ["None", "Common"] },
  "tk-bw-z-6": { rarity: ["None", "Common"] },
  "tk-bw-z-7": { rarity: ["None", "Common"] },
  "tk-bw-z-8": { rarity: ["None", "Common"] },
  "tk-bw-z-9": { rarity: ["None", "Common"] },
  "tk-dp-l-1": { rarity: ["None", "Common"] },
  "tk-dp-l-10": { rarity: ["None", "Common"] },
  "tk-dp-l-11": { rarity: ["None", "Common"] },
  "tk-dp-l-2": { rarity: ["None", "Common"] },
  "tk-dp-l-3": { rarity: ["None", "Common"] },
  "tk-dp-l-4": { rarity: ["None", "Common"] },
  "tk-dp-l-5": { rarity: ["None", "Common"] },
  "tk-dp-l-6": { rarity: ["None", "Common"] },
  "tk-dp-l-7": { rarity: ["None", "Common"] },
  "tk-dp-l-8": { rarity: ["None", "Common"] },
  "tk-dp-l-9": { rarity: ["None", "Common"] },
  "tk-dp-m-1": { rarity: ["None", "Common"] },
  "tk-dp-m-10": { rarity: ["None", "Common"] },
  "tk-dp-m-11": { rarity: ["None", "Common"] },
  "tk-dp-m-12": { rarity: ["None", "Common"] },
  "tk-dp-m-2": { rarity: ["None", "Common"] },
  "tk-dp-m-3": { rarity: ["None", "Common"] },
  "tk-dp-m-4": { rarity: ["None", "Common"] },
  "tk-dp-m-5": { rarity: ["None", "Common"] },
  "tk-dp-m-6": { rarity: ["None", "Common"] },
  "tk-dp-m-7": { rarity: ["None", "Common"] },
  "tk-dp-m-8": { rarity: ["None", "Common"] },
  "tk-dp-m-9": { rarity: ["None", "Common"] },
  "tk-ex-latia-1": { rarity: ["None", "Common"] },
  "tk-ex-latia-10": { rarity: ["None", "Common"] },
  "tk-ex-latia-2": { rarity: ["None", "Common"] },
  "tk-ex-latia-3": { rarity: ["None", "Common"] },
  "tk-ex-latia-4": { rarity: ["None", "Common"] },
  "tk-ex-latia-5": { rarity: ["None", "Common"] },
  "tk-ex-latia-6": { rarity: ["None", "Common"] },
  "tk-ex-latia-7": { rarity: ["None", "Common"] },
  "tk-ex-latia-8": { rarity: ["None", "Common"] },
  "tk-ex-latia-9": { rarity: ["None", "Common"] },
  "tk-ex-latio-1": { rarity: ["None", "Common"] },
  "tk-ex-latio-10": { rarity: ["None", "Common"] },
  "tk-ex-latio-2": { rarity: ["None", "Common"] },
  "tk-ex-latio-3": { rarity: ["None", "Common"] },
  "tk-ex-latio-4": { rarity: ["None", "Common"] },
  "tk-ex-latio-5": { rarity: ["None", "Common"] },
  "tk-ex-latio-6": { rarity: ["None", "Common"] },
  "tk-ex-latio-7": { rarity: ["None", "Common"] },
  "tk-ex-latio-8": { rarity: ["None", "Common"] },
  "tk-ex-latio-9": { rarity: ["None", "Common"] },
  "tk-ex-m-1": { rarity: ["None", "Common"] },
  "tk-ex-m-10": { rarity: ["None", "Common"] },
  "tk-ex-m-11": { rarity: ["None", "Common"] },
  "tk-ex-m-12": { rarity: ["None", "Common"] },
  "tk-ex-m-2": { rarity: ["None", "Common"] },
  "tk-ex-m-3": { rarity: ["None", "Common"] },
  "tk-ex-m-4": { rarity: ["None", "Common"] },
  "tk-ex-m-5": { rarity: ["None", "Common"] },
  "tk-ex-m-6": { rarity: ["None", "Common"] },
  "tk-ex-m-7": { rarity: ["None", "Common"] },
  "tk-ex-m-8": { rarity: ["None", "Common"] },
  "tk-ex-m-9": { rarity: ["None", "Common"] },
  "tk-ex-p-1": { rarity: ["None", "Common"] },
  "tk-ex-p-10": { rarity: ["None", "Common"] },
  "tk-ex-p-11": { rarity: ["None", "Common"] },
  "tk-ex-p-12": { rarity: ["None", "Common"] },
  "tk-ex-p-2": { rarity: ["None", "Common"] },
  "tk-ex-p-3": { rarity: ["None", "Common"] },
  "tk-ex-p-4": { rarity: ["None", "Common"] },
  "tk-ex-p-5": { rarity: ["None", "Common"] },
  "tk-ex-p-6": { rarity: ["None", "Common"] },
  "tk-ex-p-7": { rarity: ["None", "Common"] },
  "tk-ex-p-8": { rarity: ["None", "Common"] },
  "tk-ex-p-9": { rarity: ["None", "Common"] },
  "tk-hs-g-1": { rarity: ["None", "Common"] },
  "tk-hs-g-10": { rarity: ["None", "Common"] },
  "tk-hs-g-11": { rarity: ["None", "Common"] },
  "tk-hs-g-12": { rarity: ["None", "Common"] },
  "tk-hs-g-13": { rarity: ["None", "Common"] },
  "tk-hs-g-14": { rarity: ["None", "Common"] },
  "tk-hs-g-15": { rarity: ["None", "Common"] },
  "tk-hs-g-16": { rarity: ["None", "Common"] },
  "tk-hs-g-17": { rarity: ["None", "Common"] },
  "tk-hs-g-18": { rarity: ["None", "Common"] },
  "tk-hs-g-19": { rarity: ["None", "Common"] },
  "tk-hs-g-2": { rarity: ["None", "Common"] },
  "tk-hs-g-20": { rarity: ["None", "Common"] },
  "tk-hs-g-21": { rarity: ["None", "Common"] },
  "tk-hs-g-22": { rarity: ["None", "Common"] },
  "tk-hs-g-23": { rarity: ["None", "Common"] },
  "tk-hs-g-24": { rarity: ["None", "Common"] },
  "tk-hs-g-25": { rarity: ["None", "Common"] },
  "tk-hs-g-26": { rarity: ["None", "Common"] },
  "tk-hs-g-27": { rarity: ["None", "Common"] },
  "tk-hs-g-28": { rarity: ["None", "Common"] },
  "tk-hs-g-29": { rarity: ["None", "Common"] },
  "tk-hs-g-3": { rarity: ["None", "Common"] },
  "tk-hs-g-30": { rarity: ["None", "Common"] },
  "tk-hs-g-4": { rarity: ["None", "Common"] },
  "tk-hs-g-5": { rarity: ["None", "Common"] },
  "tk-hs-g-6": { rarity: ["None", "Common"] },
  "tk-hs-g-7": { rarity: ["None", "Common"] },
  "tk-hs-g-8": { rarity: ["None", "Common"] },
  "tk-hs-g-9": { rarity: ["None", "Common"] },
  "tk-hs-r-1": { rarity: ["None", "Common"] },
  "tk-hs-r-10": { rarity: ["None", "Common"] },
  "tk-hs-r-11": { rarity: ["None", "Common"] },
  "tk-hs-r-12": { rarity: ["None", "Common"] },
  "tk-hs-r-13": { rarity: ["None", "Common"] },
  "tk-hs-r-14": { rarity: ["None", "Common"] },
  "tk-hs-r-15": { rarity: ["None", "Common"] },
  "tk-hs-r-16": { rarity: ["None", "Common"] },
  "tk-hs-r-17": { rarity: ["None", "Common"] },
  "tk-hs-r-18": { rarity: ["None", "Common"] },
  "tk-hs-r-19": { rarity: ["None", "Common"] },
  "tk-hs-r-2": { rarity: ["None", "Common"] },
  "tk-hs-r-20": { rarity: ["None", "Common"] },
  "tk-hs-r-21": { rarity: ["None", "Common"] },
  "tk-hs-r-22": { rarity: ["None", "Common"] },
  "tk-hs-r-23": { rarity: ["None", "Common"] },
  "tk-hs-r-24": { rarity: ["None", "Common"] },
  "tk-hs-r-25": { rarity: ["None", "Common"] },
  "tk-hs-r-26": { rarity: ["None", "Common"] },
  "tk-hs-r-27": { rarity: ["None", "Common"] },
  "tk-hs-r-28": { rarity: ["None", "Common"] },
  "tk-hs-r-29": { rarity: ["None", "Common"] },
  "tk-hs-r-3": { rarity: ["None", "Common"] },
  "tk-hs-r-30": { rarity: ["None", "Common"] },
  "tk-hs-r-4": { rarity: ["None", "Common"] },
  "tk-hs-r-5": { rarity: ["None", "Common"] },
  "tk-hs-r-6": { rarity: ["None", "Common"] },
  "tk-hs-r-7": { rarity: ["None", "Common"] },
  "tk-hs-r-8": { rarity: ["None", "Common"] },
  "tk-hs-r-9": { rarity: ["None", "Common"] },
  "tk-sm-l-16": { rarity: ["None", "Uncommon"] },
  "tk-sm-l-30": { rarity: ["None", "Uncommon"] },
  "tk-sm-r-1": { rarity: ["None", "Common"] },
  "tk-sm-r-10": { rarity: ["None", "Common"] },
  "tk-sm-r-12": { rarity: ["None", "Common"] },
  "tk-sm-r-14": { rarity: ["None", "Common"] },
  "tk-sm-r-17": { rarity: ["None", "Uncommon"] },
  "tk-sm-r-24": { rarity: ["None", "Common"] },
  "tk-sm-r-27": { rarity: ["None", "Common"] },
  "tk-sm-r-28": { rarity: ["None", "Common"] },
  "tk-sm-r-29": { rarity: ["None", "Common"] },
  "tk-sm-r-3": { rarity: ["None", "Common"] },
  "tk-sm-r-30": { rarity: ["None", "Uncommon"] },
  "tk-sm-r-5": { rarity: ["None", "Common"] },
  "tk-sm-r-7": { rarity: ["None", "Common"] },
  "tk-sm-r-8": { rarity: ["None", "Common"] },
  "tk-sm-r-9": { rarity: ["None", "Common"] },
  "tk-xy-latia-14": { rarity: ["None", "Common"] },
  "tk-xy-latia-30": { rarity: ["None", "Common"] },
  "tk-xy-latia-4": { rarity: ["None", "Common"] },
  "tk-xy-latio-13": { rarity: ["None", "Common"] },
  "tk-xy-latio-30": { rarity: ["None", "Common"] },
  "tk-xy-n-13": { rarity: ["None", "Common"] },
  "tk-xy-n-30": { rarity: ["None", "Common"] },
  "tk-xy-p-11": { rarity: ["None", "Common"] },
  "tk-xy-p-13": { rarity: ["None", "Common"] },
  "tk-xy-p-14": { rarity: ["None", "Common"] },
  "tk-xy-p-16": { rarity: ["None", "Common"] },
  "tk-xy-p-22": { rarity: ["None", "Common"] },
  "tk-xy-p-28": { rarity: ["None", "Common"] },
  "tk-xy-p-30": { rarity: ["None", "Common"] },
  "tk-xy-p-7": { rarity: ["None", "Common"] },
  "tk-xy-su-14": { rarity: ["None", "Common"] },
  "tk-xy-su-30": { rarity: ["None", "Common"] },
  "tk-xy-su-4": { rarity: ["None", "Common"] },
  "tk-xy-sy-15": { rarity: ["None", "Common"] },
  "tk-xy-sy-30": { rarity: ["None", "Common"] },
  "xy0-1": { rarity: ["None", "Common"] },
  "xy0-10": { rarity: ["None", "Common"] },
  "xy0-11": { rarity: ["None", "Common"] },
  "xy0-12": { rarity: ["None", "Common"] },
  "xy0-13": { rarity: ["None", "Common"] },
  "xy0-14": { rarity: ["None", "Common"] },
  "xy0-15": { rarity: ["None", "Common"] },
  "xy0-16": { rarity: ["None", "Common"] },
  "xy0-17": { rarity: ["None", "Common"] },
  "xy0-18": { rarity: ["None", "Common"] },
  "xy0-19": { rarity: ["None", "Common"] },
  "xy0-2": { rarity: ["None", "Common"] },
  "xy0-20": { rarity: ["None", "Common"] },
  "xy0-21": { rarity: ["None", "Common"] },
  "xy0-22": { rarity: ["None", "Common"] },
  "xy0-23": { rarity: ["None", "Common"] },
  "xy0-24": { rarity: ["None", "Common"] },
  "xy0-25": { rarity: ["None", "Common"] },
  "xy0-26": { rarity: ["None", "Common"] },
  "xy0-27": { rarity: ["None", "Common"] },
  "xy0-28": { rarity: ["None", "Common"] },
  "xy0-29": { rarity: ["None", "Common"] },
  "xy0-3": { rarity: ["None", "Common"] },
  "xy0-30": { rarity: ["None", "Common"] },
  "xy0-31": { rarity: ["None", "Common"] },
  "xy0-32": { rarity: ["None", "Common"] },
  "xy0-33": { rarity: ["None", "Common"] },
  "xy0-34": { rarity: ["None", "Common"] },
  "xy0-35": { rarity: ["None", "Common"] },
  "xy0-36": { rarity: ["None", "Common"] },
  "xy0-37": { rarity: ["None", "Common"] },
  "xy0-38": { rarity: ["None", "Common"] },
  "xy0-39": { rarity: ["None", "Common"] },
  "xy0-4": { rarity: ["None", "Common"] },
  "xy0-5": { rarity: ["None", "Common"] },
  "xy0-6": { rarity: ["None", "Common"] },
  "xy0-7": { rarity: ["None", "Common"] },
  "xy0-8": { rarity: ["None", "Common"] },
  "xy0-9": { rarity: ["None", "Common"] },
  "xy8-146a": { rarity: ["None", "Promo"] },
};

const sameTypes = (a: readonly string[], b: readonly string[]) =>
  a.length === b.length && [...a].sort().join() === [...b].sort().join();

/** A card's rarity and types with its correction applied, where TCGdex still says what was corrected. */
export function correctedFacts<T extends { rarity: string | null; types: string[] }>(
  id: string,
  facts: T,
): T {
  const fix = CARD_FACT_CORRECTIONS[id];
  if (!fix) return facts;
  return {
    ...facts,
    rarity: fix.rarity && facts.rarity === fix.rarity[0] ? fix.rarity[1] : facts.rarity,
    types: fix.types && sameTypes(facts.types, fix.types[0]) ? [...fix.types[1]] : facts.types,
  };
}
